Repository lamkhjason/dating-website, pull requests merged in 2024-06, with the labels that each got.

#12 【css】Login, Register
  src/assets/css/Style.css
  src/pages/EditProfile.php
  src/pages/Interactions.php
  src/pages/Login.php
  src/pages/MatchedList.php
  src/pages/Profile.php
  src/pages/Register.php
Labels: デザイン・文言調整

#14 TopBar, Profile, MatchedList, Interactions
  src/assets/css/Style.css
  src/components/CommonTools.php
  src/pages/EditProfile.php
  src/pages/Interactions.php
  src/pages/Login.php
  src/pages/MatchedList.php
  src/pages/Profile.php
  src/pages/Register.php
Labels: デザイン・文言調整

#17 微調整（bindValue, checkInputValue）
  src/components/CheckValue.php
  src/components/CommonTools.php
  src/database/Pdo.php
  src/database/ProcessRegister.php
  src/database/SelectInteractions.php
  src/database/SelectProfileItem.php
  src/database/UpdateEditProfile.php
  src/pages/EditProfile.php
  src/pages/Interactions.php
  src/pages/Profile.php
Labels: システム調整

#18 【CSS】EditProfile.php
  src/assets/css/Style.css
  src/pages/EditProfile.php
  src/pages/Login.php
Labels: デザイン・文言調整

#10 CSS作成
  src/assets/css/Style.css
  src/components/CheckValue.php
  src/components/CommonTools.php
  src/database/Pdo.php
  src/database/ProcessRegister.php
  src/database/SelectInteractions.php
  src/database/SelectProfileItem.php
  src/database/UpdateEditProfile.php
  src/pages/EditProfile.php
  src/pages/Interactions.php
  src/pages/Login.php
  src/pages/MatchedList.php
  src/pages/Profile.php
  src/pages/Register.php
Labels: デザイン・文言調整

#25 【追加機能】favicon
  src/assets/icon/calendar-heart-fill.svg
  src/pages/EditProfile.php
  src/pages/Interactions.php
  src/pages/Login.php
  src/pages/MatchedList.php
  src/pages/Profile.php
  src/pages/Register.php
Labels: 機能追加

#27 【追加機能】form・textareaのplaceholder
  src/pages/EditProfile.php
  src/pages/Login.php
  src/pages/Register.php
Labels: 機能追加

#21 【追加機能】dislike-btn - Xボタン機能
  src/assets/css/Style.css
  src/database/ProcessInteractions.php
  src/pages/Interactions.php
Labels: 機能追加

#20 【追加機能】マッチング一覧の検索機能
  src/assets/css/Style.css
  src/database/SelectMatchedList.php
  src/pages/MatchedList.php
Labels: 機能追加

#28 【追加機能】パスワードハッシュ化
  src/database/ProcessLogin.php
  src/database/ProcessRegister.php
Labels: 機能追加

#29 【追加機能】ファイルの拡張子・パスワードなどの入力制御
  src/components/CheckValue.php
  src/database/ProcessRegister.php
  src/database/UpdateEditProfile.php
Labels: 機能追加

#23 【追加機能】アカウント削除機能
  src/assets/css/Style.css
  src/database/DeleteAccount.php
  src/pages/Profile.php
Labels: 機能追加

#22 【追加機能】プロフィール項目追加
  src/assets/css/Style.css
  src/database/SelectProfileItem.php
  src/database/UpdateEditProfile.php
  src/pages/EditProfile.php
  src/pages/Profile.php
Labels: 機能追加

#24 【追加機能】メッセージ機能
  src/assets/css/Style.css
  src/database/SelectMessage.php
  src/database/SendMessage.php
  src/pages/MatchedList.php
  src/pages/Message.php
Labels: 機能追加

#26 【追加機能】複数プロフィール写真機能
  src/assets/css/Style.css
  src/components/CheckValue.php
  src/database/ProcessProfilePic.php
  src/database/ProcessRegister.php
  src/database/SelectInteractions.php
  src/database/SelectMatchedList.php
  src/database/SelectProfileItem.php
  src/database/UpdateEditProfile.php
  src/js/CarouselPictures.js
  src/pages/EditProfile.php
  src/pages/EditProfilePic.php
  src/pages/Profile.php
Labels: 機能追加
