Repository lamkhjason/dating-website, pull requests merged in 2024-05, with the labels that each got.

#7 ログイン画面（html,php,LoginStatus.php）
  src/Login.html
  src/Login.php
  src/LoginStatus.php
Labels: 機能追加

#5 新規登録画面作成（奥本担当）
  src/Register.php
Labels: 機能追加

#9 リファクタリング
  .github/README.md
  assets/css/Style.css
  src/Interactions.php
  src/Register.php
  src/components/CheckValue.php
  src/components/CommonTools.php
  src/database/LoginStatus.php
  src/database/Pdo.php
  src/database/ProcessInteractions.php
  src/database/ProcessLogin.php
  src/database/ProcessRegister.php
  src/database/SelectInteractions.php
  src/database/SelectMatchedList.php
  src/database/SelectProfileItem.php
  src/database/UpdateEditProfile.php
  src/js/Congratulations.js
  src/pages/EditProfile.php
  src/pages/Interactions.php
  src/pages/Login.php
  src/pages/MatchedList.php
  src/pages/Profile.php
  src/pages/Register.php
Labels: システム調整

#13 微調整
  .github/README.md
  src/assets/css/Style.css
  src/components/CheckValue.php
  src/components/CommonTools.php
  src/database/LoginStatus.php
  src/database/Pdo.php
  src/database/ProcessInteractions.php
  src/database/ProcessLogin.php
  src/database/ProcessRegister.php
  src/database/SelectInteractions.php
  src/database/SelectMatchedList.php
  src/database/SelectProfileItem.php
  src/database/UpdateEditProfile.php
  src/pages/EditProfile.php
  src/pages/Interactions.php
  src/pages/Login.php
  src/pages/MatchedList.php
  src/pages/Profile.php
  src/pages/Register.php
Labels: システム調整

#11 CommonTools CSS
  assets/css/Style.css
  src/components/CommonTools.php
  src/pages/Interactions.php
Labels: デザイン・文言調整
